version: "3.9"
   
services:
  jupyter:
    image: jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./src/notebooks:/home/jovyan/
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    networks:
            - nginx_unicco

networks:
    nginx_unicco:
        external: true