version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx_unicco
    volumes:
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./sites:/var/www
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/

networks:
    nginx_unicco:
        external: true